#include "Courses.h"

Course courses_list[30] = { {"A_001", "Introduction to Electrical Engineering", 3},
        {"B_002", "Mechanics of Materials", 4},
        {"C_003", "Digital Logic Design", 3},
        {"D_004", "Computer Architecture", 3},
        {"E_005", "Control Systems Engineering", 4},
        {"F_006", "Data Structures and Algorithms", 3},
        {"G_007", "Engineering Thermodynamics", 3},
        {"H_008", "Structural Analysis", 4},
        {"I_009", "Signals and Systems", 3},
        {"J_010", "Engineering Mathematics", 3},
        {"K_011", "Fluid Mechanics", 4},
        {"L_012", "Engineering Economics", 3},
        {"M_013", "Power Systems Analysis", 3},
        {"N_014", "Introduction to Robotics", 4},
        {"O_015", "Engineering Ethics", 3},
        {"P_016", "Materials Science and Engineering", 3},
        {"Q_017", "Geotechnical Engineering", 4},
        {"R_018", "Electronic Circuits", 3},
        {"S_019", "Engineering Statistics", 3},
        {"T_020", "Transportation Engineering", 4},
        {"U_021", "Engineering Optimization", 3},
        {"V_022", "Introduction to Mechatronics", 3},
        {"W_023", "Engineering Dynamics", 4},
        {"X_024", "Engineering Management", 3},
        {"Y_025", "Engineering Design and Analysis", 3},
        {"Z_026", "Introduction to Aerospace Engineering", 4},
        {"A_027", "Introduction to Biomedical Engineering", 3},
        {"B_028", "Engineering Communication", 3},
        {"C_029", "Environmental Engineering", 4},
        {"D_030", "Engineering Electromagnetics", 3}
};